JS task: Support style import
TangibleInc/tangible-roller pull request #1
Opened 2022-10-18 04:54 UTC by nicolas-jaussaud

Hi,

I ran into an issue while trying to use dependencies that import CSS directly from a JavaScript file. It seems that we can use this plugin ([rollup-plugin-import-css](https://www.npmjs.com/package/rollup-plugin-import-css)) to add support for it

2022-10-18 16:12 UTC, eliot-akira commented
Thanks for pull request!

Hmm, I have some doubts about how this particular plugin implements importing CSS from JS, if it's suitable as a general purpose solution. Maybe you can convince me otherwise. :)

---

Typically, NPM dependencies are supposed to be transpiled/compiled already into a consumable format. It shouldn't be importing CSS because that's not a native feature of JavaScript.

It seems you may be loading the source files of the dependency, not the built files. Or, the dependency did not properly publish the built files, and instead published the source files expecting the user to compile them - but that's quite unusual, as most build tools do not compile files in the `node_modules` folder (because of the common convention that libraries should publish pre-built files).

Could you tell me the name of the NPM package? I'm curious to see how they expect users to import it.

---

For libraries that come with CSS files, sometimes I've had to copy the minified bundle. For example, in `tangible.config.js`:

```js
{
  task: 'copy',
  src: 'node_modules/library/dist/library.min.css',
  dest: 'assets/build',
}
```

Sometimes I just copy the CSS file manually and rename with `.scss` extension, to customize further.

---

But that might not be possible, depending on how the library uses CSS within JS, what **CSS preprocessor** it uses in its build script.

A popular way to import CSS into JS is [PostCSS](https://github.com/postcss/postcss), which is a plugin-based system for processing CSS. And commonly for React projects, people use "CSS modules" as a PostCSS plugin.

It transforms each CSS file with a local scope of randomly generated class names, which can be imported as a JavaScript object for conveniently passing to JSX.

For example, this CSS:

```css
.article {
  font-size: 16px;
}
```

..is transformed into:

```css
._article_xkpkl_10 {
  font-size: 16px;
}
```

..and is imported into JS like:


```js
import styles from './module.css'

const Article = () =>
  <div className={styles.article}>
    ...
  </div>
```

(From https://github.com/madyankin/postcss-modules)

---

However, the plugin `rollup-plugin-import-css` has a different idea of what it means to import CSS into JS.

It only supports plain CSS by default, and looking at the [code](https://github.com/jleeson/rollup-plugin-import-css/blob/master/src/index.js), the CSS is imported into JS as a simple string. That's not so useful for our purposes, and probably not many libraries use CSS in JS like this either.

2022-10-18 16:24 UTC, eliot-akira commented
I see that we're already using a plugin called [`rollup-plugin-styles`](https://github.com/Anidetrix/rollup-plugin-styles).

Currently it's just used for compiling Sass files, but it looks like the plugin supports importing CSS from JS in various ways:

> Universal Rollup plugin for styles: PostCSS, Sass, Less, Stylus and more.

So, if we wanted, we could add it for JS files. But, if I remember right, files in `node_modules` are excluded from compilation so it still wouldn't solve the original issue.

2022-10-18 16:36 UTC, eliot-akira commented
There's a comment in the JS task config [here](https://github.com/TangibleInc/tangible-roller/blob/master/task/js.js#L235-L237), which suggests that I was planning to add the `styles` plugin at some point, with related task options (like where to output the compiled CSS file).

Maybe you can see if this plugin can help solve the issue. But, like I explained above, there are several questions about if we should even support NPM packages that import CSS in JS.

2022-10-18 18:13 UTC, nicolas-jaussaud commented
Thank you for your answer!

It's really possible that I'm doing something wrong in my import

I had issues while trying to use components from the [adobe/react-spectrum package](https://www.npmjs.com/package/@adobe/react-spectrum) (the [TableView](https://react-spectrum.adobe.com/react-spectrum/TableView.html) component for example)

Here is a minimal example of what I have:

- package.json:
```json
{
  "scripts": {
    "dev": "roll dev"
  },
  "dependencies": {
    "@adobe/react-spectrum": "^3.22.0"
  },
  "devDependencies": {
    "@tangible/roller": "^1.4.2"
  }
}

```
- tangible.config.js:
```js
module.exports = {
    build: [
        {
        src: 'index.js',
        dest: 'build.js'
        }
    ]
}
```
- index.js:
```js
import { TableView } from '@react-spectrum/table'
  
console.log(TableView)
```
Which without the import-css plugin gives me the following error with `npm run dev`:
```
> dev
> roll dev

Build for development
..Building from index.js

Unexpected token (Note that you need plugins to import files that are not JavaScript)

1: .spectrum-Table_d0fc74{border-collapse:separate;border-spacing:0;isolation:isolate;outline:0; (...etc)
```

2022-10-18 21:31 UTC, eliot-akira commented
I see, in the documentation for React Spectrum, they mention that CSS import is required.

> React Spectrum works with most popular build tooling, like [Parcel](https://parceljs.org/) and [create-react-app](https://create-react-app.dev/), or lower level tools like [webpack](https://webpack.js.org/).

> The only requirement is CSS importing support. This is built into Parcel and create-react-app out of the box. If you're using React Spectrum with raw webpack, then you'll need to configure [css-loader](https://webpack.js.org/loaders/css-loader/).

(From: https://react-spectrum.adobe.com/react-spectrum/getting-started.html#build-tooling)

Looking at [the TableView component and how styles are being imported](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/table/src/TableView.tsx#L32-L33), it looks like it's using the "CSS modules" system.

I checked that the `rollup-plugin-styles` does support CSS modules: https://github.com/Anidetrix/rollup-plugin-styles/#css-modules

In the JS task, we can try adding this plugin.

```js
const styles = require('rollup-plugin-import-css')

return {
  plugins: [

    styles({
      modules: true
    }),

    json(),
   ...
```

..Hmm, looking at [the documentation for the plugin's options](https://anidetrix.github.io/rollup-plugin-styles/interfaces/types.Options.html), this will treat all CSS import from JS as locally scoped CSS modules by default. This is a similar setup as the build tool `create-react-app`, but I prefer how Next.js does it ([Adding Component-Level CSS](https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css)) by requiring the CSS file extension `.module.css` to explicitly opt-in to local scope (and otherwise treat CSS files as global). But since we're trying to support a third-party library, it expects this default behavior.

Another thing to note is that the `styles` plugin has a "mode" option. The relevant values are:

> - "inject" (default) - Embeds CSS inside JS and injects it into <head> at runtime.
> - "extract" - Extract CSS to the same location where JS file is generated but with .css extension. You can also set extraction path manually, relative to output dir/output file's basedir, but not outside of it.

I suppose the default behavior is acceptable, but I'm not too comfortable with it. This is part of the reason why I hadn't added support for CSS modules - I prefer to keep styles separate from JS.

I did notice the JS task has an option called `rollupPlugins` ([here](https://github.com/TangibleInc/tangible-roller/blob/324fe42d5d4b0ca11b43eb0b87f866f2e32e94f3/task/js.js#L271)). Maybe we can try that first, to only add the `styles` plugin for this specific task.

In tangible.config.js:

```js
const styles = require('rollup-plugin-import-css') 

module.exports = {
  build: [
    {
      src: 'assets/src/something.js',
      dest: 'assets/build/something.min.js',
      rollupPlugins: [
      ]
    }
  ]
}
```

2022-10-20 00:22 UTC, nicolas-jaussaud commented
Thank you for your detailed answer and all the explanations about PostCSS, CSS modules and how it's different from importing CSS directly 

I tried to update my tangible.config.js to use rollup-plugin-styles:
```js
const styles = require('rollup-plugin-styles')

module.exports = {
  build: [
    {
      src: 'index.js',
      dest: 'build.js',
      rollupPlugins: [
        styles({
          modules: true
        })
      ]
    }
  ]
}
```
But while running `npm run dev`, I got the following:
```
> dev
> roll dev

Build for development
..Building from index.js

[styles] ./node_modules/@react-spectrum/table/dist/main.css:1:1: Unknown word
```
The command never complete, and the build file is never generated

Something I noticed is that while in the [source files](https://github.com/adobe/react-spectrum/tree/main/packages/@react-spectrum/table/src) styles are imported as a CSS module, when used as an npm package components are imported from a different file (@react-spectrum/table/dist/module.js), that is not on github 

This file seems to import CSS directly:
```tsx
import "./main.css";
```

Maybe instead of this:
```js
import { TableView } from '@react-spectrum/table'
```
I could try to do something like this, to use the source file instead:
```js
import { TableView } from '@react-spectrum/table/src/TableView.tsx'
```
But I'm not sure it's a good way to handle the issue

2022-10-20 16:45 UTC, eliot-akira requested changes
I looked into how these build tools handle style imports from JS, and learned that by default they enable CSS modules for file extension `.module.css`.

- [Parcel: CSS modules](https://parceljs.org/languages/css/#css-modules)
- [Create React App: Adding a CSS Modules Stylesheet](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)

Adobe's React Spectrum library uses Parcel in their build script, but has CSS modules enabled for `.css` in general.

Another twist is that their published packages contain:

- `*.css` in `src` - CSS modules imported from JS
- `*.css` in `dist` - Compiled CSS imported from JS

In your original pull request description, I noticed the error message shows the latter with randomized CSS class names. So they do publish the compiled CSS, but still expect library users to handle the import from JS. I wish their published JS didn't import CSS at all - in my opinion, that would have been a better approach for a general-purpose library.

---

I experimented with a local temporary project - after studying the documentation and some trial and error, I figured out the ideal configuration. Please see the suggested changes, particularly in `task/js.js`.

The options are fairly self-explanatory. By default, Roller can support CSS modules for `.module.css`, and treat `.css` files as plain CSS. That should be compatible with React Spectrum's published files. It will also minify the CSS and produce a source map.

I changed the default [mode](https://anidetrix.github.io/rollup-plugin-styles/interfaces/types.Options.html#mode) to `extract`, because I'm not a fan of the `inject` method - it bundles CSS as a string in JS, then injects it into `<head>` element at runtime. I prefer CSS to be enqueued normally as a separate file.

There's an additional change necessary for this extract method, but I couldn't figure out how to add a file in this GitHub review interface. In [`task/index.js` on line 66](https://github.com/TangibleInc/tangible-roller/blob/91a1a5ee0df4493bd76831d707afc0f0e09736e5/task/index.js#L66), if you could change it to:

```js
    // For styles plugin
    assetFileNames: task.task === 'sass' ? '[name]' : '[name].module[extname]',
```

That defines the extracted CSS file name. The pattern `[name]` was not a good option for CSS imported from JS, because it could overwrite an existing built file from another task. So it will have the extension `.module.css` to differentiate it.

I also added a task option `styles` so that the above behavior can be customized as needed.

Would you mind testing this on your side to confirm it works?

(You can remove the previously suggested `rollupPlugins` option in `tangible.config.js`.)

---

..What I'm not totally sure is the mode "extract". Maybe "inject" is more convenient, and there's no practical advantage in extracting the CSS. It's an extra step to enqueue the CSS file, and the styles are only needed after the JS renders on the client side. Would you agree?

Edit: I tried the "inject" method, and the resulting JS file with bundled CSS can get pretty big. Also, an advantage of producing separate JS and CSS files is that the browser can load and process them in parallel. OK, so I think the "extract" mode is better.

2022-10-20 23:11 UTC, eliot-akira approved these changes

2022-10-20 23:13 UTC, merged

2022-10-20 23:15 UTC, eliot-akira commented
OK, merged! Thanks for the contribution. I'll do a quick test tomorrow, update the package version, and publish it with command `npm publish --access public`.

2022-10-20 23:20 UTC, nicolas-jaussaud commented
Hi,

It seems that I can't accept requested changes, because I'm the author of the pull request and not a reviewer so I added your changes in a new commit, alongside with the change in task/index.js

I tested the last changes on my side and I confirm that everything is now working as expected 

As someone not really familiar with how the build process works, I think I also prefer the "extract' method. It's not intuitive to understand where the CSS comes from when it uses the "inject" method

I just saw that you merged while I was writing this, thanks again for your patience and all your explanations!

2022-10-20 23:46 UTC, eliot-akira commented
> It seems that I can't accept requested changes, because I'm the author of the pull request and not a reviewer

Oh, interesting to hear. I looked into it, and I think I solved it by changing the base permissions for organization members from Read to Write.

![image](https://user-images.githubusercontent.com/5352434/197078995-51e9671f-b9ef-4a2e-94a8-cc75183892d6.png)

(From: https://github.com/organizations/TangibleInc/settings/member_privileges)

This PR was my first time using the GitHub feature for "request changes". It's a nice workflow with writing suggested changes directly in the review comment, even better if you could have just clicked on every change to add commits.

Overall, there are various aspects of GitHub that I like more than Bitbucket, so I'll consider moving some of our repos (the free plugins/modules) over here.

2022-10-21 12:59 UTC, eliot-akira commented
OK, version 1.4.3 is published.

In your local project (the one with React Spectrum), you can run `npm update` and it should update the installed Roller to the newest version.